version: '3'

tasks:
  local:up:
    desc: "Run dependencies only"
    cmds:
      - docker compose -f docker-compose.yaml up -d postgres redis zookeeper kafka jaeger otel-collector grafana loki
      - sleep 5
      - docker compose -f docker-compose.yaml up -d migrate
  local:logs:
    desc: "Show logs"
    cmds:
      - docker compose -f docker-compose.yaml logs
  local:down:
    desc: "Shut down deps"
    cmds: 
      - docker compose -f docker-compose.yaml down

  clean:
    desc: "Clean up containers, images, and volumes"
    cmds:
      - docker compose down -v --rmi all
      - docker system prune -f

  status:
    desc: "Show status of all containers"
    cmds:
      - docker compose ps