FROM golang:1.23-alpine

WORKDIR /app/contracts-service


COPY contracts-service/go.mod contracts-service/go.sum ./

RUN go mod download

COPY ./contracts-service/ ./


EXPOSE 44045

# CMD ["ls", "contracts-service"]

# CMD ["ls", "&&", "cd contracts-service", "&&", "ls"]

CMD ["go", "run", "./cmd/main.go"]

# FROM golang:1.23-alpine AS builder

# WORKDIR /app/contracts-service

# COPY contracts-service/go.mod contracts-service/go.mod

# RUN cd contracts-service && go mod download

# COPY ./contracts-service/ ./contracts-service/

# RUN cd contracts-service && CGO_ENABLED=0 GOOS=linux go build -o /contracts-service-binary ./cmd/main.go

# FROM alpine:latest
    
# WORKDIR /app


# COPY --from=builder ./contracts-service-binary .

# EXPOSE 44045

# CMD ["ls"]